/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package node_util;

import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import static node_util.AppendFile.setFileNameWithFolder;
import static node_util.FormMain.escreverArquivoConfiguracao;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Taffrel Xavier <taffarel_deus@hotmail.com>
 */
public class FormJDialogSettings extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public FormJDialogSettings(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();

        Map<String, String> env = System.getenv();

        String[] data = env.get("Path").split(";");

        for (String value : data) {
            if (value.contains("mysql")) {
                jMysqlDir.setText(value);
            }
        }

        jRootProjeto.setText(AppendFile.getValueByKeyName("root_dir"));

        jNomeProjeto.setText(AppendFile.getValueByKeyName("app_name"));

        jPorta.setText(AppendFile.getValueByKeyName("porta"));

        jNomeBancoDeDados.setText(AppendFile.getValueByKeyName("db_name"));

        //jMysqlDir.setText(AppendFile.getValueByKeyName("mysql_dir"));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jNomeProjeto = new javax.swing.JTextField();
        jPorta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jNomeBancoDeDados = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jRootProjeto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jMysqlDir = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurações do Projeto");
        setResizable(false);

        jNomeProjeto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jPorta.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Nome do Projeto:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Porta da Aplicação (Encontrar no www, da basta bin):");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jNomeBancoDeDados.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jNomeBancoDeDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomeBancoDeDadosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Nome do Banco de Dados:");

        jCheckBox1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jCheckBox1.setText("Com banco de dados?");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Root do Projeto:");

        jRootProjeto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jRootProjeto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jRootProjetoFocusLost(evt);
            }
        });
        jRootProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRootProjetoActionPerformed(evt);
            }
        });
        jRootProjeto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRootProjetoKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Caminho do MYSQL:");

        jMysqlDir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNomeBancoDeDados)
                    .addComponent(jMysqlDir)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jNomeProjeto)
                    .addComponent(jRootProjeto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPorta)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jCheckBox1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRootProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNomeProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMysqlDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNomeBancoDeDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String root = jRootProjeto.getText().trim();
        String appName = jNomeProjeto.getText().trim();
        String porta = jPorta.getText().trim();
        String db_name = jNomeBancoDeDados.getText().trim();
        String mysqlDir = jMysqlDir.getText().trim();

        String fileNameSettings = root + "\\settings.txt";

        if (root.equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o root do projeto.");
        } else if (appName.equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o nome do projeto.");
        } else if (porta.equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o número da porta.");
        } else if (db_name.equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o nome do Banco de Dados, se existir.");
        } else if (mysqlDir.equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o nome do caminho do Mysql");
        } else {
            escreverArquivoConfiguracao(root);

            setFileNameWithFolder(fileNameSettings);

            File fileSettings = new File(fileNameSettings);

            if (!fileSettings.exists()) {
                try {
                    fileSettings.createNewFile();
                } catch (IOException ex) {
                    Logger.getLogger(FormJDialogSettings.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                System.out.println(fileSettings.canExecute());
                System.out.println(fileSettings.canRead());
                System.out.println(fileSettings.canWrite());
                try {
                  fileSettings.delete();  
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null,e.getStackTrace());
                }
                
            }

            
            AppendFile.writeFile("root_dir", root);
            
            System.out.println(appName);
            
            AppendFile.writeFile("app_name", appName);
            
            AppendFile.writeFile("porta", porta);

            AppendFile.writeFile("db_name", db_name);

            AppendFile.writeFile("mysql_dir", mysqlDir);

            FormMain formUtil = new FormMain();

            File file = new File(root + "\\cmd");

            if (!file.exists()) {
                file.mkdir();
                formUtil.executarInstrucoes(root);
            } else {
                formUtil.executarInstrucoes(root);
            }

            this.setVisible(false);

            //formUtil.setVisible(true);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jNomeBancoDeDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomeBancoDeDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNomeBancoDeDadosActionPerformed

    private void jRootProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRootProjetoActionPerformed
        // TODO add your handling code here:
        System.out.println(evt.getWhen());
    }//GEN-LAST:event_jRootProjetoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRootProjetoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRootProjetoKeyPressed
        // TODO add your handling code here:


    }//GEN-LAST:event_jRootProjetoKeyPressed

    private void jRootProjetoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRootProjetoFocusLost
        // TODO add your handling code here:
        String rootProjeto = jRootProjeto.getText().trim();

        if (rootProjeto.length() > 0) {

            File file = new File(rootProjeto);

            if (file.isDirectory()) {

                jNomeProjeto.setText(file.getName());

                jNomeBancoDeDados.setText(file.getName());

            }
        }

    }//GEN-LAST:event_jRootProjetoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormJDialogSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormJDialogSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormJDialogSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormJDialogSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            FormJDialogSettings dialog = new FormJDialogSettings(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jMysqlDir;
    private javax.swing.JTextField jNomeBancoDeDados;
    private javax.swing.JTextField jNomeProjeto;
    private javax.swing.JTextField jPorta;
    private javax.swing.JTextField jRootProjeto;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
